name: Docker Image CI

on:
  push:
    branches: [ "main" , "test" ]

env:
  IMAGE_NAME: clock-rest-api

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s)
      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
